spring.application.name=bank
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_app
spring.datasource.username=grand_user
spring.datasource.password=capital_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cash.type=simple
balance.increment.rate=10
balance.max.rate=207
