version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: local-postgres-grand-capital
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bank_app
      POSTGRES_USER: grand_user
      POSTGRES_PASSWORD: capital_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: